/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java11.docker.tips.and.tricks;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Java 11 - step 0");
    }
}
